version: "2"
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    links:
      - mongo
    environment:
      - PORT=3000
      - JWT_KEY=abcd
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=searchapi
    command: npm run-script dev
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data-mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  data-mongo: